spring:
  datasource:
    druid:
      filters: mergeStat,wall,logback
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 6000
      validation-query: SELECT 'x'
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
#      shiro数据源，用于权限相关
      shiroData:
        url: jdbc:mysql://localhost:3306/test?useSSL=false
        username: root
        password: password
        driverClassName: com.mysql.jdbc.Driver
       #数据源1 业务数据
      datasource1:
        url: jdbc:mysql://localhost:3306/db_rvwc?characterEncoding=utf8
        username: root
        password: password
        driverClassName: com.mysql.jdbc.Driver

  thymeleaf:
      prefix: classpath:/templates/
#      国际化引用
  messages:
    basename: classpath:i18n/messages*.properties

logging:
    config: classpath:logback-spring.xml

redis:
  shiro:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password:
server:
  port: 8080
  session:
    timeout: 1



